[cosmic-ray]
module-path = "src"
timeout = 7
baseline = "baseline.json"
exclude-modules = ["tests/*", "src/*/__init__py"]
test-command = "pytest tests -1 -x --maxfail=2 --disable-warnings"
test-runner = "cosmic_ray.testing.pytest.runner"
exclude-modules = [
    "tests/*"
]
limit = 5

[cosmic-ray.distributor]
name = "local"
pool-size = 3